name: Build EXE

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install pyinstaller pillow pytesseract

      - name: Build
        run: pyinstaller --onefile --windowed main.py

      - name: Upload EXE
        uses: actions/upload-artifact@v5
        with:
          name: HolyWorld-Analyzer
          path: dist/main.exe
